### ISSUE TITLE
Command \Ref 已经被定义导致编译不出

### ISSUE THREAD

**Issue by pumc-zhou** [sailist/LaTeXdoc#4]
我的编译配置是：
xelatex.exe --shell-escape -8bit -synctex=1 -interaction=nonstopmode %.tex
可以调用底层命令，编译minted
报错为：
Command \Ref already defined. ...olor{airforceblue}{\ref{#1}：\nameref{#1}}}
第二个报错为：
I can't write on file `external/example_listing.tex'. \begin{texcode}
你给的编译配置没看太懂，与我日常接触的不一致，希望指点更多。

**Comment by sailist** [comment]
不清楚 %.tex 在这里是不是有具体文件名代替，能定位到具体行吗？直接在 repo 目录下运行我给出的编译命令是否还报这一错误？在我的电脑上给出的命令能够完美无错的编译成功。

另外文件有一定更新，记得 `git pull` 后再运行编译命令

**Comment by pumc-zhou** [comment]
我是用的是texlive+texstudio，在texstudio的options>command中可以设置编译命令，
`xelatex.exe --shell-escape -8bit -synctex=1 -interaction=nonstopmode %.tex`
%.tex 在这里代替具体文件名
编译后的输出就是如下
`xelatex.exe --shell-escape -8bit -synctex=1 -interaction=nonstopmode "LaTeXTutorial".tex`

### 具体行
`\usepackage[printwatermark,disablegeometry]{xwatermark}`
`I can't write on file `external/example_listing.tex'. \begin{texcode}`
`Emergency stop. \begin{texcode}`
`Package loading is aborted because of missing \pdf@unescapehex.`
`fixltx2e is not required with releases after 2015(fixltx2e) All fixes are now in the LaTeX kernel.`
`Redefining CJKfamily `\CJKrmdefault' (SimSun(0)).`
`No file LaTeXTutorial.bbl.`
麻烦你看看

**Comment by sailist** [comment]
确认是否最终仍然输出了 pdf 文件，如果是，那么影响不大；如果否，

尝试以下方法：


根据 [here](https://tex.stackexchange.com/questions/401139/tcolorbox-package-returns-missing-pdfunescapehex-warning) 的答案，将 `preamble/package.tex` 中的 `tcolorbox` 的引入替换为 

```
\usepackage[many]{tcolorbox}
```

随后全局搜索 `externalize listing=example_listing,` 将 `\newtcblisting` 命令下定义的该行参数全部删除

**Comment by pumc-zhou** [comment]
最终无法输出PDF文件
是删除`externalize listing=example_listing`这一行。
还是把
`\newtcblisting{texbreakcode}{breakable,
    arc=0mm,drop shadow,
    %externalize listing=example_listing,
    listing engine=minted,
    minted style=colorful,
    minted language=tex,
    minted options={fontsize=\small,breaklines,autogobble,numbersep=0mm},
    colback=codeback,
    colframe=codeback,
    listing only,
    left=0mm,enhanced,
}`
这个全部删完。
还是把
`{breakable,
    arc=0mm,drop shadow,
    %externalize listing=example_listing,
    listing engine=minted,
    minted style=colorful,
    minted language=tex,
    minted options={fontsize=\small,breaklines,autogobble,numbersep=0mm},
    colback=codeback,
    colframe=codeback,
    listing only,
    left=0mm,enhanced,
}`
删掉。

**Comment by sailist** [comment]
删一行，请至少仔细看完我回复的，做过尝试后再行询问；另外我的电脑上确实不存在这个问题，我也是通过搜索得出的这个结论，如果还是无法编译成功，请尝试自行解决。
